from os import listdir
from os.path import isfile, join
import random
import time
import json

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

from jdlv_data import *
from jdlv_model import *
from jdlv_outils import *

def clean_grid (grid):
    for i in range (default_grid_size):
        for j in range (default_grid_size):
            grid.cases [i][j]['s'] = death_status
            grid.cases [i][j]['c'] = death_color
    return grid

def make_pikachu (grid, i, j,color):
    try:
        #grid = clean_grid (grid)
        cases = grid.cases
        cases [i] [j] ['s'] = life_status
        cases [i] [j] ['c'] = color10
        cases [i] [j+1] ['s'] = life_status
        cases [i] [j+1] ['c'] = color2
        cases [i] [j+2] ['s'] = life_status
        cases [i] [j+2] ['c'] = color2
        cases [i] [j+3] ['s'] = life_status
        cases [i] [j+3] ['c'] = color2
        cases [i] [j+4] ['s'] = life_status
        cases [i] [j+4] ['c'] = color10
        cases [i] [j+5] ['s'] = life_status
        cases [i] [j+5] ['c'] = color10
        cases [i] [j+6] ['s'] = life_status
        cases [i] [j+6] ['c'] = color1
        cases [i] [j+7] ['s'] = life_status
        cases [i] [j+7] ['c'] = color1
        cases [i] [j+8] ['s'] = life_status
        cases [i] [j+8] ['c'] = color2
        cases [i] [j+9] ['s'] = life_status
        cases [i] [j+9] ['c'] = color5
        cases [i] [j+10] ['s'] = life_status
        cases [i] [j+10] ['c'] = color6
        cases [i] [j+11] ['s'] = life_status
        cases [i] [j+11] ['c'] = color6
        cases [i] [j+12] ['s'] = life_status
        cases [i] [j+12] ['c'] = color10
        cases [i-1] [j-1] ['s'] = life_status
        cases [i-1] [j-1] ['c'] = color10
        cases [i-1] [j] ['s'] = life_status
        cases [i-1] [j] ['c'] = color2
        cases [i-1] [j+1] ['s'] = life_status
        cases [i-1] [j+1] ['c'] = color2
        cases [i-1] [j+2] ['s'] = life_status
        cases [i-1] [j+2] ['c'] = color2
        cases [i-1] [j+3] ['s'] = life_status
        cases [i-1] [j+3] ['c'] = color2
        cases [i-1] [j+4] ['s'] = life_status
        cases [i-1] [j+4] ['c'] = color4
        cases [i-1] [j+5] ['s'] = life_status
        cases [i-1] [j+5] ['c'] = color10
        cases [i-1] [j+6] ['s'] = life_status
        cases [i-1] [j+6] ['c'] = color2
        cases [i-1] [j+7] ['s'] = life_status
        cases [i-1] [j+7] ['c'] = color2
        cases [i-1] [j+8] ['s'] = life_status
        cases [i-1] [j+8] ['c'] = color2
        cases [i-1] [j+9] ['s'] = life_status
        cases [i-1] [j+9] ['c'] = color5
        cases [i-1] [j+10] ['s'] = life_status
        cases [i-1] [j+10] ['c'] = color5
        cases [i-1] [j+11] ['s'] = life_status
        cases [i-1] [j+11] ['c'] = color10
        cases [i-1] [j+12] ['s'] = life_status
        cases [i-1] [j+12] ['c'] = color10
        cases [i-1] [j+13] ['s'] = life_status
        cases [i-1] [j+13] ['c'] = color10
        cases [i-2] [j-1] ['s'] = life_status
        cases [i-2] [j-1] ['c'] = color10
        cases [i-2] [j] ['s'] = life_status
        cases [i-2] [j] ['c'] = color10
        cases [i-2] [j+1] ['s'] = life_status
        cases [i-2] [j+1] ['c'] = color2
        cases [i-2] [j+2] ['s'] = life_status
        cases [i-2] [j+2] ['c'] = color2
        cases [i-2] [j+3] ['s'] = life_status
        cases [i-2] [j+3] ['c'] = color2
        cases [i-2] [j+4] ['s'] = life_status
        cases [i-2] [j+4] ['c'] = color2
        cases [i-2] [j+5] ['s'] = life_status
        cases [i-2] [j+5] ['c'] = color2
        cases [i-2] [j+6] ['s'] = life_status
        cases [i-2] [j+6] ['c'] = color2
        cases [i-2] [j+7] ['s'] = life_status
        cases [i-2] [j+7] ['c'] = color2
        cases [i-2] [j+8] ['s'] = life_status
        cases [i-2] [j+8] ['c'] = color2
        cases [i-2] [j+9] ['s'] = life_status
        cases [i-2] [j+9] ['c'] = color2
        cases [i-2] [j+10] ['s'] = life_status
        cases [i-2] [j+10] ['c'] = color5
        cases [i-2] [j+11] ['s'] = life_status
        cases [i-2] [j+11] ['c'] = color10
        cases [i-2] [j+12] ['s'] = life_status
        cases [i-2] [j+12] ['c'] = color10
        cases [i-2] [j+13] ['s'] = life_status
        cases [i-2] [j+13] ['c'] = color5
        cases [i-2] [j+14] ['s'] = life_status
        cases [i-2] [j+14] ['c'] = color10
        cases [i-3] [j-1] ['s'] = life_status
        cases [i-3] [j-1] ['c'] = color10
        cases [i-3] [j] ['s'] = life_status
        cases [i-3] [j] ['c'] = color4
        cases [i-3] [j+1] ['s'] = life_status
        cases [i-3] [j+1] ['c'] = color2
        cases [i-3] [j+2] ['s'] = life_status
        cases [i-3] [j+2] ['c'] = color2
        cases [i-3] [j+3] ['s'] = life_status
        cases [i-3] [j+3] ['c'] = color2
        cases [i-3] [j+4] ['s'] = life_status
        cases [i-3] [j+4] ['c'] = color2
        cases [i-3] [j+5] ['s'] = life_status
        cases [i-3] [j+5] ['c'] = color2
        cases [i-3] [j+6] ['s'] = life_status
        cases [i-3] [j+6] ['c'] = color2
        cases [i-3] [j+7] ['s'] = life_status
        cases [i-3] [j+7] ['c'] = color2
        cases [i-3] [j+8] ['s'] = life_status
        cases [i-3] [j+8] ['c'] = color2
        cases [i-3] [j+9] ['s'] = life_status
        cases [i-3] [j+9] ['c'] = color2
        cases [i-3] [j+10] ['s'] = life_status
        cases [i-3] [j+10] ['c'] = color10
        cases [i-3] [j+11] ['s'] = life_status
        cases [i-3] [j+11] ['c'] = color6
        cases [i-3] [j+12] ['s'] = life_status
        cases [i-3] [j+12] ['c'] = color6
        cases [i-3] [j+13] ['s'] = life_status
        cases [i-3] [j+13] ['c'] = color10
        cases [i-3] [j+14] ['s'] = life_status
        cases [i-3] [j+14] ['c'] = color5
        cases [i-3] [j+15] ['s'] = life_status
        cases [i-3] [j+15] ['c'] = color10
        cases [i-4] [j] ['s'] = life_status
        cases [i-4] [j] ['c'] = color10
        cases [i-4] [j+1] ['s'] = life_status
        cases [i-4] [j+1] ['c'] = color2
        cases [i-4] [j+2] ['s'] = life_status
        cases [i-4] [j+2] ['c'] = color2
        cases [i-4] [j+3] ['s'] = life_status
        cases [i-4] [j+3] ['c'] = color2
        cases [i-4] [j+4] ['s'] = life_status
        cases [i-4] [j+4] ['c'] = color2
        cases [i-4] [j+5] ['s'] = life_status
        cases [i-4] [j+5] ['c'] = color2
        cases [i-4] [j+6] ['s'] = life_status
        cases [i-4] [j+6] ['c'] = color2
        cases [i-4] [j+7] ['s'] = life_status
        cases [i-4] [j+7] ['c'] = color2
        cases [i-4] [j+8] ['s'] = life_status
        cases [i-4] [j+8] ['c'] = color2
        cases [i-4] [j+9] ['s'] = life_status
        cases [i-4] [j+9] ['c'] = color5
        cases [i-4] [j+10] ['s'] = life_status
        cases [i-4] [j+10] ['c'] = color10
        cases [i-4] [j+11] ['s'] = life_status
        cases [i-4] [j+11] ['c'] = color6
        cases [i-4] [j+12] ['s'] = life_status
        cases [i-4] [j+12] ['c'] = color10
        cases [i-4] [j+13] ['s'] = life_status
        cases [i-4] [j+13] ['c'] = color5
        cases [i-4] [j+14] ['s'] = life_status
        cases [i-4] [j+14] ['c'] = color5
        cases [i-4] [j+15] ['s'] = life_status
        cases [i-4] [j+15] ['c'] = color10
        cases [i-5] [j+1] ['s'] = life_status
        cases [i-5] [j+1] ['c'] = color10
        cases [i-5] [j+2] ['s'] = life_status
        cases [i-5] [j+2] ['c'] = color2
        cases [i-5] [j+3] ['s'] = life_status
        cases [i-5] [j+3] ['c'] = color2
        cases [i-5] [j+4] ['s'] = life_status
        cases [i-5] [j+4] ['c'] = color2
        cases [i-5] [j+5] ['s'] = life_status
        cases [i-5] [j+5] ['c'] = color2
        cases [i-5] [j+6] ['s'] = life_status
        cases [i-5] [j+6] ['c'] = color2
        cases [i-5] [j+7] ['s'] = life_status
        cases [i-5] [j+7] ['c'] = color2
        cases [i-5] [j+8] ['s'] = life_status
        cases [i-5] [j+8] ['c'] = color2
        cases [i-5] [j+9] ['s'] = life_status
        cases [i-5] [j+9] ['c'] = color2
        cases [i-5] [j+10] ['s'] = life_status
        cases [i-5] [j+10] ['c'] = color10
        cases [i-5] [j+11] ['s'] = life_status
        cases [i-5] [j+11] ['c'] = color10
        cases [i-5] [j+12] ['s'] = life_status
        cases [i-5] [j+12] ['c'] = color5
        cases [i-5] [j+13] ['s'] = life_status
        cases [i-5] [j+13] ['c'] = color5
        cases [i-5] [j+14] ['s'] = life_status
        cases [i-5] [j+14] ['c'] = color10
        cases [i-6] [j+2] ['s'] = life_status
        cases [i-6] [j+2] ['c'] = color10
        cases [i-6] [j+3] ['s'] = life_status
        cases [i-6] [j+3] ['c'] = color2
        cases [i-6] [j+4] ['s'] = life_status
        cases [i-6] [j+4] ['c'] = color2
        cases [i-6] [j+5] ['s'] = life_status
        cases [i-6] [j+5] ['c'] = color2
        cases [i-6] [j+6] ['s'] = life_status
        cases [i-6] [j+6] ['c'] = color10
        cases [i-6] [j+7] ['s'] = life_status
        cases [i-6] [j+7] ['c'] = color10
        cases [i-6] [j+8] ['s'] = life_status
        cases [i-6] [j+8] ['c'] = color2
        cases [i-6] [j+9] ['s'] = life_status
        cases [i-6] [j+9] ['c'] = color2
        cases [i-6] [j+10] ['s'] = life_status
        cases [i-6] [j+10] ['c'] = color6
        cases [i-6] [j+11] ['s'] = life_status
        cases [i-6] [j+11] ['c'] = color10
        cases [i-6] [j+12] ['s'] = life_status
        cases [i-6] [j+12] ['c'] = color5
        cases [i-6] [j+13] ['s'] = life_status
        cases [i-6] [j+13] ['c'] = color5
        cases [i-6] [j+14] ['s'] = life_status
        cases [i-6] [j+14] ['c'] = color5
        cases [i-6] [j+15] ['s'] = life_status
        cases [i-6] [j+15] ['c'] = color10
        cases [i-7] [j+2] ['s'] = life_status
        cases [i-7] [j+2] ['c'] = color10
        cases [i-7] [j+3] ['s'] = life_status
        cases [i-7] [j+3] ['c'] = color2
        cases [i-7] [j+4] ['s'] = life_status
        cases [i-7] [j+4] ['c'] = color5
        cases [i-7] [j+5] ['s'] = life_status
        cases [i-7] [j+5] ['c'] = color10
        cases [i-7] [j+8] ['s'] = life_status
        cases [i-7] [j+8] ['c'] = color10
        cases [i-7] [j+9] ['s'] = life_status
        cases [i-7] [j+9] ['c'] = color10
        cases [i-7] [j+10] ['s'] = life_status
        cases [i-7] [j+10] ['c'] = color6
        cases [i-7] [j+11] ['s'] = life_status
        cases [i-7] [j+11] ['c'] = color6
        cases [i-7] [j+12] ['s'] = life_status
        cases [i-7] [j+12] ['c'] = color10
        cases [i-7] [j+13] ['s'] = life_status
        cases [i-7] [j+13] ['c'] = color5
        cases [i-7] [j+14] ['s'] = life_status
        cases [i-7] [j+14] ['c'] = color5
        cases [i-7] [j+15] ['s'] = life_status
        cases [i-7] [j+15] ['c'] = color5
        cases [i-7] [j+16] ['s'] = life_status
        cases [i-7] [j+16] ['c'] = color10
        cases [i-8] [j+3] ['s'] = life_status
        cases [i-8] [j+3] ['c'] = color10
        cases [i-8] [j+4] ['s'] = life_status
        cases [i-8] [j+4] ['c'] = color2
        cases [i-8] [j+5] ['s'] = life_status
        cases [i-8] [j+5] ['c'] = color10
        cases [i-8] [j+10] ['s'] = life_status
        cases [i-8] [j+10] ['c'] = color10
        cases [i-8] [j+11] ['s'] = life_status
        cases [i-8] [j+11] ['c'] = color10
        cases [i-8] [j+12] ['s'] = life_status
        cases [i-8] [j+12] ['c'] = color10
        cases [i-8] [j+13] ['s'] = life_status
        cases [i-8] [j+13] ['c'] = color2
        cases [i-8] [j+14] ['s'] = life_status
        cases [i-8] [j+14] ['c'] = color5
        cases [i-8] [j+15] ['s'] = life_status
        cases [i-8] [j+15] ['c'] = color5
        cases [i-8] [j+16] ['s'] = life_status
        cases [i-8] [j+16] ['c'] = color5
        cases [i-8] [j+17] ['s'] = life_status
        cases [i-8] [j+17] ['c'] = color10
        cases [i-9] [j+3] ['s'] = life_status
        cases [i-9] [j+3] ['c'] = color10
        cases [i-9] [j+4] ['s'] = life_status
        cases [i-9] [j+4] ['c'] = color6
        cases [i-9] [j+5] ['s'] = life_status
        cases [i-9] [j+5] ['c'] = color10
        cases [i-9] [j+13] ['s'] = life_status
        cases [i-9] [j+13] ['c'] = color10
        cases [i-9] [j+14] ['s'] = life_status
        cases [i-9] [j+14] ['c'] = color2
        cases [i-9] [j+15] ['s'] = life_status
        cases [i-9] [j+15] ['c'] = color5
        cases [i-9] [j+16] ['s'] = life_status
        cases [i-9] [j+16] ['c'] = color5
        cases [i-9] [j+17] ['s'] = life_status
        cases [i-9] [j+17] ['c'] = color10
        cases [i-10] [j+4] ['s'] = life_status
        cases [i-10] [j+4] ['c'] = color10
        cases [i-10] [j+5] ['s'] = life_status
        cases [i-10] [j+5] ['c'] = color10
        cases [i-10] [j+14] ['s'] = life_status
        cases [i-10] [j+14] ['c'] = color10
        cases [i-10] [j+15] ['s'] = life_status
        cases [i-10] [j+15] ['c'] = color2
        cases [i-10] [j+16] ['s'] = life_status
        cases [i-10] [j+16] ['c'] = color10
        cases [i-11] [j+15] ['s'] = life_status
        cases [i-11] [j+15] ['c'] = color10
        cases [i+1] [j+1] ['s'] = life_status
        cases [i+1] [j+1] ['c'] = color10
        cases [i+1] [j+2] ['s'] = life_status
        cases [i+1] [j+2] ['c'] = color5
        cases [i+1] [j+3] ['s'] = life_status
        cases [i+1] [j+3] ['c'] = color2
        cases [i+1] [j+4] ['s'] = life_status
        cases [i+1] [j+4] ['c'] = color2
        cases [i+1] [j+5] ['s'] = life_status
        cases [i+1] [j+5] ['c'] = color2
        cases [i+1] [j+6] ['s'] = life_status
        cases [i+1] [j+6] ['c'] = color1
        cases [i+1] [j+7] ['s'] = life_status
        cases [i+1] [j+7] ['c'] = color5
        cases [i+1] [j+8] ['s'] = life_status
        cases [i+1] [j+8] ['c'] = color5
        cases [i+1] [j+9] ['s'] = life_status
        cases [i+1] [j+9] ['c'] = color5
        cases [i+1] [j+10] ['s'] = life_status
        cases [i+1] [j+10] ['c'] = color5
        cases [i+1] [j+11] ['s'] = life_status
        cases [i+1] [j+11] ['c'] = color5
        cases [i+1] [j+12] ['s'] = life_status
        cases [i+1] [j+12] ['c'] = color10
        cases [i+2] [j] ['s'] = life_status
        cases [i+2] [j] ['c'] = color10
        cases [i+2] [j+1] ['s'] = life_status
        cases [i+2] [j+1] ['c'] = color2
        cases [i+2] [j+2] ['s'] = life_status
        cases [i+2] [j+2] ['c'] = color5
        cases [i+2] [j+3] ['s'] = life_status
        cases [i+2] [j+3] ['c'] = color5
        cases [i+2] [j+4] ['s'] = life_status
        cases [i+2] [j+4] ['c'] = color5
        cases [i+2] [j+5] ['s'] = life_status
        cases [i+2] [j+5] ['c'] = color5
        cases [i+2] [j+6] ['s'] = life_status
        cases [i+2] [j+6] ['c'] = color5
        cases [i+2] [j+7] ['s'] = life_status
        cases [i+2] [j+7] ['c'] = color5
        cases [i+2] [j+8] ['s'] = life_status
        cases [i+2] [j+8] ['c'] = color10
        cases [i+2] [j+9] ['s'] = life_status
        cases [i+2] [j+9] ['c'] = color5
        cases [i+2] [j+10] ['s'] = life_status
        cases [i+2] [j+10] ['c'] = color5
        cases [i+2] [j+11] ['s'] = life_status
        cases [i+2] [j+11] ['c'] = color6
        cases [i+2] [j+12] ['s'] = life_status
        cases [i+2] [j+12] ['c'] = color10
        cases [i+3] [j] ['s'] = life_status
        cases [i+3] [j] ['c'] = color10
        cases [i+3] [j+1] ['s'] = life_status
        cases [i+3] [j+1] ['c'] = color10
        cases [i+3] [j+2] ['s'] = life_status
        cases [i+3] [j+2] ['c'] = color10
        cases [i+3] [j+3] ['s'] = life_status
        cases [i+3] [j+3] ['c'] = color2
        cases [i+3] [j+4] ['s'] = life_status
        cases [i+3] [j+4] ['c'] = color2
        cases [i+3] [j+5] ['s'] = life_status
        cases [i+3] [j+5] ['c'] = color2
        cases [i+3] [j+6] ['s'] = life_status
        cases [i+3] [j+6] ['c'] = color2
        cases [i+3] [j+7] ['s'] = life_status
        cases [i+3] [j+7] ['c'] = color10
        cases [i+3] [j+8] ['s'] = life_status
        cases [i+3] [j+8] ['c'] = color2
        cases [i+3] [j+9] ['s'] = life_status
        cases [i+3] [j+9] ['c'] = color5
        cases [i+3] [j+10] ['s'] = life_status
        cases [i+3] [j+10] ['c'] = color5
        cases [i+3] [j+11] ['s'] = life_status
        cases [i+3] [j+11] ['c'] = color5
        cases [i+3] [j+12] ['s'] = life_status
        cases [i+3] [j+12] ['c'] = color10
        cases [i+4] [j+1] ['s'] = life_status
        cases [i+4] [j+1] ['c'] = color10
        cases [i+4] [j+2] ['s'] = life_status
        cases [i+4] [j+2] ['c'] = color5
        cases [i+4] [j+3] ['s'] = life_status
        cases [i+4] [j+3] ['c'] = color10
        cases [i+4] [j+4] ['s'] = life_status
        cases [i+4] [j+4] ['c'] = color2
        cases [i+4] [j+5] ['s'] = life_status
        cases [i+4] [j+5] ['c'] = color2
        cases [i+4] [j+6] ['s'] = life_status
        cases [i+4] [j+6] ['c'] = color2
        cases [i+4] [j+7] ['s'] = life_status
        cases [i+4] [j+7] ['c'] = color2
        cases [i+4] [j+8] ['s'] = life_status
        cases [i+4] [j+8] ['c'] = color10
        cases [i+4] [j+9] ['s'] = life_status
        cases [i+4] [j+9] ['c'] = color5
        cases [i+4] [j+10] ['s'] = life_status
        cases [i+4] [j+10] ['c'] = color5
        cases [i+4] [j+11] ['s'] = life_status
        cases [i+4] [j+11] ['c'] = color5
        cases [i+4] [j+12] ['s'] = life_status
        cases [i+4] [j+12] ['c'] = color10
        cases [i+5] [j+1] ['s'] = life_status
        cases [i+5] [j+1] ['c'] = color10
        cases [i+5] [j+2] ['s'] = life_status
        cases [i+5] [j+2] ['c'] = color10
        cases [i+5] [j+3] ['s'] = life_status
        cases [i+5] [j+3] ['c'] = color10
        cases [i+5] [j+4] ['s'] = life_status
        cases [i+5] [j+4] ['c'] = color10
        cases [i+5] [j+5] ['s'] = life_status
        cases [i+5] [j+5] ['c'] = color10
        cases [i+5] [j+6] ['s'] = life_status
        cases [i+5] [j+6] ['c'] = color5
        cases [i+5] [j+7] ['s'] = life_status
        cases [i+5] [j+7] ['c'] = color5
        cases [i+5] [j+8] ['s'] = life_status
        cases [i+5] [j+8] ['c'] = color5
        cases [i+5] [j+9] ['s'] = life_status
        cases [i+5] [j+9] ['c'] = color5
        cases [i+5] [j+10] ['s'] = life_status
        cases [i+5] [j+10] ['c'] = color5
        cases [i+5] [j+11] ['s'] = life_status
        cases [i+5] [j+11] ['c'] = color10
        cases [i+6] [j+6] ['s'] = life_status
        cases [i+6] [j+6] ['c'] = color10
        cases [i+6] [j+7] ['s'] = life_status
        cases [i+6] [j+7] ['c'] = color10
        cases [i+6] [j+8] ['s'] = life_status
        cases [i+6] [j+8] ['c'] = color10
        cases [i+6] [j+9] ['s'] = life_status
        cases [i+6] [j+9] ['c'] = color5
        cases [i+6] [j+10] ['s'] = life_status
        cases [i+6] [j+10] ['c'] = color10
        cases [i+6] [j+11] ['s'] = life_status
        cases [i+6] [j+11] ['c'] = color10
        cases [i+7] [j+7] ['s'] = life_status
        cases [i+7] [j+7] ['c'] = color10
        cases [i+7] [j+8] ['s'] = life_status
        cases [i+7] [j+8] ['c'] = color2
        cases [i+7] [j+9] ['s'] = life_status
        cases [i+7] [j+9] ['c'] = color2
        cases [i+7] [j+10] ['s'] = life_status
        cases [i+7] [j+10] ['c'] = color5
        cases [i+7] [j+11] ['s'] = life_status
        cases [i+7] [j+11] ['c'] = color10
        cases [i+8] [j+8] ['s'] = life_status
        cases [i+8] [j+8] ['c'] = color10
        cases [i+8] [j+9] ['s'] = life_status
        cases [i+8] [j+9] ['c'] = color10
        cases [i+8] [j+10] ['s'] = life_status
        cases [i+8] [j+10] ['c'] = color10

    except:
         pass
    return grid


def make_salamèche (grid, i, j,color):
    #grid = clean_grid (grid)
    cases = grid.cases
    cases [i] [j] ['s'] = life_status
    cases [i] [j] ['c'] = color10
    cases [i] [j+10] ['s'] = life_status
    cases [i] [j+10] ['c'] = color10
    cases [i] [j+11] ['s'] = life_status
    cases [i] [j+11] ['c'] = color10
    cases [i] [j+12] ['s'] = life_status
    cases [i] [j+12] ['c'] = color10
    cases [i] [j+13] ['s'] = life_status
    cases [i] [j+13] ['c'] = color10
    cases [i+1] [j-1] ['s'] = life_status
    cases [i+1] [j-1] ['c'] = color10
    cases [i+1] [j] ['s'] = life_status
    cases [i+1] [j] ['c'] = color1
    cases [i+1] [j+1] ['s'] = life_status
    cases [i+1] [j+1] ['c'] = color10
    cases [i+1] [j+9] ['s'] = life_status
    cases [i+1] [j+9] ['c'] = color10
    cases [i+1] [j+10] ['s'] = life_status
    cases [i+1] [j+10] ['c'] = color7
    cases [i+1] [j+11] ['s'] = life_status
    cases [i+1] [j+11] ['c'] = color7
    cases [i+1] [j+12] ['s'] = life_status
    cases [i+1] [j+12] ['c'] = color7
    cases [i+1] [j+13] ['s'] = life_status
    cases [i+1] [j+13] ['c'] = color7
    cases [i+1] [j+14] ['s'] = life_status
    cases [i+1] [j+14] ['c'] = color10
    cases [i+2] [j-2] ['s'] = life_status
    cases [i+2] [j-2] ['c'] = color10
    cases [i+2] [j-1] ['s'] = life_status
    cases [i+2] [j-1] ['c'] = color1
    cases [i+2] [j] ['s'] = life_status
    cases [i+2] [j] ['c'] = color1
    cases [i+2] [j+1] ['s'] = life_status
    cases [i+2] [j+1] ['c'] = color10
    cases [i+2] [j+8] ['s'] = life_status
    cases [i+2] [j+8] ['c'] = color10
    cases [i+2] [j+9] ['s'] = life_status
    cases [i+2] [j+9] ['c'] = color7
    cases [i+2] [j+10] ['s'] = life_status
    cases [i+2] [j+10] ['c'] = color7
    cases [i+2] [j+11] ['s'] = life_status
    cases [i+2] [j+11] ['c'] = color7
    cases [i+2] [j+12] ['s'] = life_status
    cases [i+2] [j+12] ['c'] = color7
    cases [i+2] [j+13] ['s'] = life_status
    cases [i+2] [j+13] ['c'] = color7
    cases [i+2] [j+14] ['s'] = life_status
    cases [i+2] [j+14] ['c'] = color7
    cases [i+2] [j+15] ['s'] = life_status
    cases [i+2] [j+15] ['c'] = color10
    cases [i+3] [j-2] ['s'] = life_status
    cases [i+3] [j-2] ['c'] = color10
    cases [i+3] [j-1] ['s'] = life_status
    cases [i+3] [j-1] ['c'] = color1
    cases [i+3] [j] ['s'] = life_status
    cases [i+3] [j] ['c'] = color1
    cases [i+3] [j+1] ['s'] = life_status
    cases [i+3] [j+1] ['c'] = color10
    cases [i+3] [j+8] ['s'] = life_status
    cases [i+3] [j+8] ['c'] = color10
    cases [i+3] [j+9] ['s'] = life_status
    cases [i+3] [j+9] ['c'] = color7
    cases [i+3] [j+10] ['s'] = life_status
    cases [i+3] [j+10] ['c'] = color7
    cases [i+3] [j+11] ['s'] = life_status
    cases [i+3] [j+11] ['c'] = color7
    cases [i+3] [j+12] ['s'] = life_status
    cases [i+3] [j+12] ['c'] = color7
    cases [i+3] [j+13] ['s'] = life_status
    cases [i+3] [j+13] ['c'] = color7
    cases [i+3] [j+14] ['s'] = life_status
    cases [i+3] [j+14] ['c'] = color7
    cases [i+3] [j+15] ['s'] = life_status
    cases [i+3] [j+15] ['c'] = color10
    cases [i+4] [j-3] ['s'] = life_status
    cases [i+4] [j-3] ['c'] = color10
    cases [i+4] [j-2] ['s'] = life_status
    cases [i+4] [j-2] ['c'] = color1
    cases [i+4] [j-1] ['s'] = life_status
    cases [i+4] [j-1] ['c'] = color1
    cases [i+4] [j] ['s'] = life_status
    cases [i+4] [j] ['c'] = color1
    cases [i+4] [j+1] ['s'] = life_status
    cases [i+4] [j+1] ['c'] = color1
    cases [i+4] [j+2] ['s'] = life_status
    cases [i+4] [j+2] ['c'] = color10 
    cases [i+4] [j+7] ['s'] = life_status
    cases [i+4] [j+7] ['c'] = color10
    cases [i+4] [j+8] ['s'] = life_status
    cases [i+4] [j+8] ['c'] = color7
    cases [i+4] [j+9] ['s'] = life_status
    cases [i+4] [j+9] ['c'] = color7
    cases [i+4] [j+10] ['s'] = life_status
    cases [i+4] [j+10] ['c'] = color7
    cases [i+4] [j+11] ['s'] = life_status
    cases [i+4] [j+11] ['c'] = color7
    cases [i+4] [j+12] ['s'] = life_status
    cases [i+4] [j+12] ['c'] = color7
    cases [i+4] [j+13] ['s'] = life_status
    cases [i+4] [j+13] ['c'] = color7
    cases [i+4] [j+14] ['s'] = life_status
    cases [i+4] [j+14] ['c'] = color7
    cases [i+4] [j+15] ['s'] = life_status
    cases [i+4] [j+15] ['c'] = color7
    cases [i+4] [j+16] ['s'] = life_status
    cases [i+4] [j+16] ['c'] = color10
    cases [i+5] [j-3] ['s'] = life_status
    cases [i+5] [j-3] ['c'] = color10
    cases [i+5] [j-2] ['s'] = life_status
    cases [i+5] [j-2] ['c'] = color1
    cases [i+5] [j-1] ['s'] = life_status
    cases [i+5] [j-1] ['c'] = color2
    cases [i+5] [j] ['s'] = life_status
    cases [i+5] [j] ['c'] = color1
    cases [i+5] [j+1] ['s'] = life_status
    cases [i+5] [j+1] ['c'] = color1
    cases [i+5] [j+2] ['s'] = life_status
    cases [i+5] [j+2] ['c'] = color10
    cases [i+5] [j+7] ['s'] = life_status
    cases [i+5] [j+7] ['c'] = color10
    cases [i+5] [j+8] ['s'] = life_status
    cases [i+5] [j+8] ['c'] = color7
    cases [i+5] [j+9] ['s'] = life_status
    cases [i+5] [j+9] ['c'] = color7
    cases [i+5] [j+10] ['s'] = life_status
    cases [i+5] [j+10] ['c'] = color7
    cases [i+5] [j+11] ['s'] = life_status
    cases [i+5] [j+11] ['c'] = color10
    cases [i+5] [j+12] ['s'] = life_status
    cases [i+5] [j+12] ['c'] = color4
    cases [i+5] [j+13] ['s'] = life_status
    cases [i+5] [j+13] ['c'] = color7
    cases [i+5] [j+14] ['s'] = life_status
    cases [i+5] [j+14] ['c'] = color7
    cases [i+5] [j+15] ['s'] = life_status
    cases [i+5] [j+15] ['c'] = color7
    cases [i+5] [j+16] ['s'] = life_status
    cases [i+5] [j+16] ['c'] = color7
    cases [i+5] [j+17] ['s'] = life_status
    cases [i+5] [j+17] ['c'] = color10
    cases [i+6] [j-3] ['s'] = life_status
    cases [i+6] [j-3] ['c'] = color10
    cases [i+6] [j-2] ['s'] = life_status
    cases [i+6] [j-2] ['c'] = color1
    cases [i+6] [j-1] ['s'] = life_status
    cases [i+6] [j-1] ['c'] = color2
    cases [i+6] [j] ['s'] = life_status
    cases [i+6] [j] ['c'] = color2
    cases [i+6] [j+1] ['s'] = life_status
    cases [i+6] [j+1] ['c'] = color1
    cases [i+6] [j+2] ['s'] = life_status
    cases [i+6] [j+2] ['c'] = color10
    cases [i+6] [j+6] ['s'] = life_status
    cases [i+6] [j+6] ['c'] = color10
    cases [i+6] [j+7] ['s'] = life_status
    cases [i+6] [j+7] ['c'] = color7
    cases [i+6] [j+8] ['s'] = life_status
    cases [i+6] [j+8] ['c'] = color7
    cases [i+6] [j+9] ['s'] = life_status
    cases [i+6] [j+9] ['c'] = color7
    cases [i+6] [j+10] ['s'] = life_status
    cases [i+6] [j+10] ['c'] = color7
    cases [i+6] [j+11] ['s'] = life_status
    cases [i+6] [j+11] ['c'] = color10
    cases [i+6] [j+12] ['s'] = life_status
    cases [i+6] [j+12] ['c'] = color10
    cases [i+6] [j+13] ['s'] = life_status
    cases [i+6] [j+13] ['c'] = color7
    cases [i+6] [j+14] ['s'] = life_status
    cases [i+6] [j+14] ['c'] = color7
    cases [i+6] [j+15] ['s'] = life_status
    cases [i+6] [j+15] ['c'] = color7
    cases [i+6] [j+16] ['s'] = life_status
    cases [i+6] [j+16] ['c'] = color7
    cases [i+6] [j+17] ['s'] = life_status
    cases [i+6] [j+17] ['c'] = color10
    cases [i+7] [j-2] ['s'] = life_status
    cases [i+7] [j-2] ['c'] = color10
    cases [i+7] [j-1] ['s'] = life_status
    cases [i+7] [j-1] ['c'] = color10
    cases [i+7] [j] ['s'] = life_status
    cases [i+7] [j] ['c'] = color2
    cases [i+7] [j+1] ['s'] = life_status
    cases [i+7] [j+1] ['c'] = color10
    cases [i+7] [j+6] ['s'] = life_status
    cases [i+7] [j+6] ['c'] = color10
    cases [i+7] [j+7] ['s'] = life_status
    cases [i+7] [j+7] ['c'] = color7
    cases [i+7] [j+8] ['s'] = life_status
    cases [i+7] [j+8] ['c'] = color7
    cases [i+7] [j+9] ['s'] = life_status
    cases [i+7] [j+9] ['c'] = color7
    cases [i+7] [j+10] ['s'] = life_status
    cases [i+7] [j+10] ['c'] = color7
    cases [i+7] [j+11] ['s'] = life_status
    cases [i+7] [j+11] ['c'] = color10
    cases [i+7] [j+12] ['s'] = life_status
    cases [i+7] [j+12] ['c'] = color10
    cases [i+7] [j+13] ['s'] = life_status
    cases [i+7] [j+13] ['c'] = color7
    cases [i+7] [j+14] ['s'] = life_status
    cases [i+7] [j+14] ['c'] = color7
    cases [i+7] [j+15] ['s'] = life_status
    cases [i+7] [j+15] ['c'] = color7
    cases [i+7] [j+16] ['s'] = life_status
    cases [i+7] [j+16] ['c'] = color7
    cases [i+7] [j+17] ['s'] = life_status
    cases [i+7] [j+17] ['c'] = color10
    cases [i+8] [j-1] ['s'] = life_status
    cases [i+8] [j-1] ['c'] = color10
    cases [i+8] [j] ['s'] = life_status
    cases [i+8] [j] ['c'] = color7
    cases [i+8] [j+1] ['s'] = life_status
    cases [i+8] [j+1] ['c'] = color10
    cases [i+8] [j+5] ['s'] = life_status
    cases [i+8] [j+5] ['c'] = color10
    cases [i+8] [j+6] ['s'] = life_status
    cases [i+8] [j+6] ['c'] = color7
    cases [i+8] [j+7] ['s'] = life_status
    cases [i+8] [j+7] ['c'] = color7
    cases [i+8] [j+8] ['s'] = life_status
    cases [i+8] [j+8] ['c'] = color7
    cases [i+8] [j+9] ['s'] = life_status
    cases [i+8] [j+9] ['c'] = color7
    cases [i+8] [j+10] ['s'] = life_status
    cases [i+8] [j+10] ['c'] = color7
    cases [i+8] [j+11] ['s'] = life_status
    cases [i+8] [j+11] ['c'] = color7
    cases [i+8] [j+12] ['s'] = life_status
    cases [i+8] [j+12] ['c'] = color7
    cases [i+8] [j+13] ['s'] = life_status
    cases [i+8] [j+13] ['c'] = color7
    cases [i+8] [j+14] ['s'] = life_status
    cases [i+8] [j+14] ['c'] = color7
    cases [i+8] [j+15] ['s'] = life_status
    cases [i+8] [j+15] ['c'] = color7
    cases [i+8] [j+16] ['s'] = life_status
    cases [i+8] [j+16] ['c'] = color10
    cases [i+9] [j-1] ['s'] = life_status
    cases [i+9] [j-1] ['c'] = color10
    cases [i+9] [j] ['s'] = life_status
    cases [i+9] [j] ['c'] = color7
    cases [i+9] [j+1] ['s'] = life_status
    cases [i+9] [j+1] ['c'] = color7
    cases [i+9] [j+2] ['s'] = life_status
    cases [i+9] [j+2] ['c'] = color10
    cases [i+9] [j+4] ['s'] = life_status
    cases [i+9] [j+4] ['c'] = color10
    cases [i+9] [j+5] ['s'] = life_status
    cases [i+9] [j+5] ['c'] = color7
    cases [i+9] [j+6] ['s'] = life_status
    cases [i+9] [j+6] ['c'] = color7
    cases [i+9] [j+7] ['s'] = life_status
    cases [i+9] [j+7] ['c'] = color7
    cases [i+9] [j+8] ['s'] = life_status
    cases [i+9] [j+8] ['c'] = color7
    cases [i+9] [j+9] ['s'] = life_status
    cases [i+9] [j+9] ['c'] = color7
    cases [i+9] [j+10] ['s'] = life_status
    cases [i+9] [j+10] ['c'] = color7
    cases [i+9] [j+11] ['s'] = life_status
    cases [i+9] [j+11] ['c'] = color7
    cases [i+9] [j+12] ['s'] = life_status
    cases [i+9] [j+12] ['c'] = color7
    cases [i+9] [j+13] ['s'] = life_status
    cases [i+9] [j+13] ['c'] = color7
    cases [i+9] [j+14] ['s'] = life_status
    cases [i+9] [j+14] ['c'] = color10
    cases [i+9] [j+15] ['s'] = life_status
    cases [i+9] [j+15] ['c'] = color10
    cases [i+10] [j] ['s'] = life_status
    cases [i+10] [j] ['c'] = color10
    cases [i+10] [j+1] ['s'] = life_status
    cases [i+10] [j+1] ['c'] = color7
    cases [i+10] [j+2] ['s'] = life_status
    cases [i+10] [j+2] ['c'] = color7
    cases [i+10] [j+3] ['s'] = life_status
    cases [i+10] [j+3] ['c'] = color10
    cases [i+10] [j+4] ['s'] = life_status
    cases [i+10] [j+4] ['c'] = color10
    cases [i+10] [j+5] ['s'] = life_status
    cases [i+10] [j+5] ['c'] = color7
    cases [i+10] [j+6] ['s'] = life_status
    cases [i+10] [j+6] ['c'] = color7
    cases [i+10] [j+7] ['s'] = life_status
    cases [i+10] [j+7] ['c'] = color7
    cases [i+10] [j+8] ['s'] = life_status
    cases [i+10] [j+8] ['c'] = color10
    cases [i+10] [j+9] ['s'] = life_status
    cases [i+10] [j+9] ['c'] = color7
    cases [i+10] [j+10] ['s'] = life_status
    cases [i+10] [j+10] ['c'] = color7
    cases [i+10] [j+11] ['s'] = life_status
    cases [i+10] [j+11] ['c'] = color10
    cases [i+10] [j+12] ['s'] = life_status
    cases [i+10] [j+12] ['c'] = color10
    cases [i+10] [j+13] ['s'] = life_status
    cases [i+10] [j+13] ['c'] = color10
    cases [i+11] [j] ['s'] = life_status
    cases [i+11] [j] ['c'] = color10
    cases [i+11] [j+1] ['s'] = life_status
    cases [i+11] [j+1] ['c'] = color7
    cases [i+11] [j+2] ['s'] = life_status
    cases [i+11] [j+2] ['c'] = color7
    cases [i+11] [j+3] ['s'] = life_status
    cases [i+11] [j+3] ['c'] = color10
    cases [i+11] [j+4] ['s'] = life_status
    cases [i+11] [j+4] ['c'] = color7
    cases [i+11] [j+5] ['s'] = life_status
    cases [i+11] [j+5] ['c'] = color7
    cases [i+11] [j+6] ['s'] = life_status
    cases [i+11] [j+6] ['c'] = color7
    cases [i+11] [j+7] ['s'] = life_status
    cases [i+11] [j+7] ['c'] = color7
    cases [i+11] [j+8] ['s'] = life_status
    cases [i+11] [j+8] ['c'] = color7
    cases [i+11] [j+9] ['s'] = life_status
    cases [i+11] [j+9] ['c'] = color10
    cases [i+11] [j+10] ['s'] = life_status
    cases [i+11] [j+10] ['c'] = color2
    cases [i+11] [j+11] ['s'] = life_status
    cases [i+11] [j+11] ['c'] = color2
    cases [i+11] [j+12] ['s'] = life_status
    cases [i+11] [j+12] ['c'] = color10
    cases [i+12] [j+1] ['s'] = life_status
    cases [i+12] [j+1] ['c'] = color10
    cases [i+12] [j+2] ['s'] = life_status
    cases [i+12] [j+2] ['c'] = color7
    cases [i+12] [j+3] ['s'] = life_status
    cases [i+12] [j+3] ['c'] = color10
    cases [i+12] [j+4] ['s'] = life_status
    cases [i+12] [j+4] ['c'] = color7
    cases [i+12] [j+5] ['s'] = life_status
    cases [i+12] [j+5] ['c'] = color7
    cases [i+12] [j+6] ['s'] = life_status
    cases [i+12] [j+6] ['c'] = color7
    cases [i+12] [j+7] ['s'] = life_status
    cases [i+12] [j+7] ['c'] = color10
    cases [i+12] [j+8] ['s'] = life_status
    cases [i+12] [j+8] ['c'] = color10
    cases [i+12] [j+9] ['s'] = life_status
    cases [i+12] [j+9] ['c'] = color2
    cases [i+12] [j+10] ['s'] = life_status
    cases [i+12] [j+10] ['c'] = color2
    cases [i+12] [j+11] ['s'] = life_status
    cases [i+12] [j+11] ['c'] = color2
    cases [i+12] [j+12] ['s'] = life_status
    cases [i+12] [j+12] ['c'] = color10
    cases [i+13] [j+2] ['s'] = life_status
    cases [i+13] [j+2] ['c'] = color10
    cases [i+13] [j+3] ['s'] = life_status
    cases [i+13] [j+3] ['c'] = color10
    cases [i+13] [j+4] ['s'] = life_status
    cases [i+13] [j+4] ['c'] = color7
    cases [i+13] [j+5] ['s'] = life_status
    cases [i+13] [j+5] ['c'] = color7
    cases [i+13] [j+6] ['s'] = life_status
    cases [i+13] [j+6] ['c'] = color7
    cases [i+13] [j+7] ['s'] = life_status
    cases [i+13] [j+7] ['c'] = color7
    cases [i+13] [j+8] ['s'] = life_status
    cases [i+13] [j+8] ['c'] = color2
    cases [i+13] [j+9] ['s'] = life_status
    cases [i+13] [j+9] ['c'] = color2
    cases [i+13] [j+10] ['s'] = life_status
    cases [i+13] [j+10] ['c'] = color2
    cases [i+13] [j+11] ['s'] = life_status
    cases [i+13] [j+11] ['c'] = color10
    cases [i+13] [j+12] ['s'] = life_status
    cases [i+13] [j+12] ['c'] = color4
    cases [i+13] [j+13] ['s'] = life_status
    cases [i+13] [j+13] ['c'] = color10
    cases [i+14] [j+3] ['s'] = life_status
    cases [i+14] [j+3] ['c'] = color10
    cases [i+14] [j+4] ['s'] = life_status
    cases [i+14] [j+4] ['c'] = color10
    cases [i+14] [j+5] ['s'] = life_status
    cases [i+14] [j+5] ['c'] = color7
    cases [i+14] [j+6] ['s'] = life_status
    cases [i+14] [j+6] ['c'] = color7
    cases [i+14] [j+7] ['s'] = life_status
    cases [i+14] [j+7] ['c'] = color7
    cases [i+14] [j+8] ['s'] = life_status
    cases [i+14] [j+8] ['c'] = color2
    cases [i+14] [j+9] ['s'] = life_status
    cases [i+14] [j+9] ['c'] = color2
    cases [i+14] [j+10] ['s'] = life_status
    cases [i+14] [j+10] ['c'] = color10
    cases [i+14] [j+11] ['s'] = life_status
    cases [i+14] [j+11] ['c'] = color10
    cases [i+14] [j+12] ['s'] = life_status
    cases [i+14] [j+12] ['c'] = color10
    cases [i+15] [j+4] ['s'] = life_status
    cases [i+15] [j+4] ['c'] = color10
    cases [i+15] [j+5] ['s'] = life_status
    cases [i+15] [j+5] ['c'] = color10
    cases [i+15] [j+6] ['s'] = life_status
    cases [i+15] [j+6] ['c'] = color7
    cases [i+15] [j+7] ['s'] = life_status
    cases [i+15] [j+7] ['c'] = color10
    cases [i+15] [j+8] ['s'] = life_status
    cases [i+15] [j+8] ['c'] = color10
    cases [i+15] [j+9] ['s'] = life_status
    cases [i+15] [j+9] ['c'] = color10
    cases [i+16] [j+4] ['s'] = life_status
    cases [i+16] [j+4] ['c'] = color10
    cases [i+16] [j+5] ['s'] = life_status
    cases [i+16] [j+5] ['c'] = color4
    cases [i+16] [j+6] ['s'] = life_status
    cases [i+16] [j+6] ['c'] = color7
    cases [i+16] [j+7] ['s'] = life_status
    cases [i+16] [j+7] ['c'] = color4
    cases [i+16] [j+8] ['s'] = life_status
    cases [i+16] [j+8] ['c'] = color10
    cases [i+17] [j+4] ['s'] = life_status
    cases [i+17] [j+4] ['c'] = color10
    cases [i+17] [j+5] ['s'] = life_status
    cases [i+17] [j+5] ['c'] = color10
    cases [i+17] [j+6] ['s'] = life_status
    cases [i+17] [j+6] ['c'] = color10
    cases [i+17] [j+7] ['s'] = life_status
    cases [i+17] [j+7] ['c'] = color10
    return grid

def make_canon_a_glisseur (grid, i, j,color):
    #grid = clean_grid (grid)
    cases = grid.cases
    cases [i] [j] ['s'] = life_status
    cases [i] [j] ['c'] = color7
    cases [i] [j+1] ['s'] = life_status
    cases [i] [j+1] ['c'] = color7
    cases [i+1] [j] ['s'] = life_status
    cases [i+1] [j] ['c'] = color7
    cases [i+1] [j+1] ['s'] = life_status
    cases [i+1] [j+1] ['c'] = color7
    cases [i] [j+10] ['s'] = life_status
    cases [i] [j+10] ['c'] = color7
    cases [i+1] [j+10] ['s'] = life_status
    cases [i+1] [j+10] ['c'] = color7
    cases [i+2] [j+10] ['s'] = life_status
    cases [i+2] [j+10] ['c'] = color7
    cases [i-1] [j+11] ['s'] = life_status
    cases [i-1] [j+11] ['c'] = color7
    cases [i+3] [j+11] ['s'] = life_status
    cases [i+3] [j+11] ['c'] = color7
    cases [i-2] [j+12] ['s'] = life_status
    cases [i-2] [j+12] ['c'] = color7
    cases [i+4] [j+12] ['s'] = life_status
    cases [i+4] [j+12] ['c'] = color7
    cases [i-2] [j+13] ['s'] = life_status
    cases [i-2] [j+13] ['c'] = color7
    cases [i+4] [j+13] ['s'] = life_status
    cases [i+4] [j+13] ['c'] = color7
    cases [i+1] [j+14] ['s'] = life_status
    cases [i+1] [j+14] ['c'] = color7
    cases [i-1] [j+15] ['s'] = life_status
    cases [i-1] [j+15] ['c'] = color7
    cases [i+3] [j+15] ['s'] = life_status
    cases [i+3] [j+15] ['c'] = color7
    cases [i] [j+16] ['s'] = life_status
    cases [i] [j+16] ['c'] = color7
    cases [i+1] [j+16] ['s'] = life_status
    cases [i+1] [j+16] ['c'] = color7
    cases [i+2] [j+16] ['s'] = life_status
    cases [i+2] [j+16] ['c'] = color7
    cases [i+1] [j+17] ['s'] = life_status
    cases [i+1] [j+17] ['c'] = color7
    cases [i-2] [j+20] ['s'] = life_status
    cases [i-2] [j+20] ['c'] = color7
    cases [i-1] [j+20] ['s'] = life_status
    cases [i-1] [j+20] ['c'] = color7
    cases [i] [j+20] ['s'] = life_status
    cases [i] [j+20] ['c'] = color7
    cases [i-2] [j+21] ['c'] = color7
    cases [i-1] [j+21] ['s'] = life_status
    cases [i-1] [j+21] ['c'] = color7
    cases [i] [j+21] ['s'] = life_status
    cases [i] [j+21] ['c'] = color7
    cases [i-3] [j+22] ['c'] = color7
    cases [i-3] [j+22] ['s'] = life_status
    cases [i+1] [j+22] ['c'] = color7
    cases [i+1] [j+22] ['s'] = life_status
    cases [i-3] [j+24] ['c'] = color7
    cases [i-3] [j+24] ['s'] = life_status
    cases [i-4] [j+24] ['c'] = color7
    cases [i-4] [j+24] ['s'] = life_status
    cases [i+1] [j+24] ['c'] = color7
    cases [i+1] [j+24] ['s'] = life_status
    cases [i+2] [j+24] ['c'] = color7
    cases [i+2] [j+24] ['s'] = life_status
    cases [i-1] [j+33] ['s'] = life_status
    cases [i-1] [j+33] ['c'] = color7
    cases [i-1] [j+34] ['s'] = life_status
    cases [i-1] [j+34] ['c'] = color7
    cases [i-2] [j+33] ['s'] = life_status
    cases [i-2] [j+33] ['c'] = color7
    cases [i-2] [j+34] ['s'] = life_status
    cases [i-2] [j+34] ['c'] = color7
    
    return grid


def make_glisseur (grid, i, j ,color):
    cases = grid.cases
    cases [i] [j] ['s'] = life_status
    cases [i] [j] ['c'] = color1
    cases [i+2] [j] ['s'] = life_status
    cases [i+2] [j] ['c'] = color1
    cases [i] [j+3] ['s'] = life_status
    cases [i] [j+3] ['c'] = color1
    cases [i+3] [j+1] ['s'] = life_status
    cases [i+3] [j+1] ['c'] = color1
    cases [i+3] [j+2] ['s'] = life_status
    cases [i+3] [j+2] ['c'] = color1
    cases [i+3] [j+3] ['s'] = life_status
    cases [i+3] [j+3] ['c'] = color1
    cases [i+3] [j+4] ['s'] = life_status
    cases [i+3] [j+4] ['c'] = color1
    cases [i+1] [j+4] ['s'] = life_status
    cases [i+1] [j+4] ['c'] = color1
    cases [i+2] [j+4] ['s'] = life_status
    cases [i+2] [j+4] ['c'] = color1
    return grid
    


def apply_game_of_life_rules (grid):
    cases = grid.cases # cases is a list of lists of dictionnaries
    next_grid = Grid (len (cases))
    next_cases = next_grid.cases
    for i in range (1,len (cases) - 1 ):
        for j in range (21):
            next_grid.cases [i] [j] ['s'] = cases [i] [j] ['s']
            next_grid.cases [i] [j] ['c'] = cases [i] [j] ['c']
    for i in range (len (cases) - 1): 
        for j in range (21, len (cases) - 1):
            voisins = get_voisins (cases, i, j)
            nbre_alive_voisins = count_alive_voisins (voisins)
            if nbre_alive_voisins == 3:
                next_cases [i] [j] = revive_case (next_cases [i] [j])
            elif nbre_alive_voisins <= 1 or nbre_alive_voisins >= 4:
                next_cases [i] [j] = kill_case (next_cases [i] [j])
            else:
                next_cases [i] [j] = cases [i] [j]
    return next_grid


def apply_rules (grid, compteur):
    next_grid = grid
    if compteur <=0:
        next_grid = \
            make_pikachu (next_grid, 30, compteur + 70, color)
        next_grid = \
            make_salamèche (next_grid, 20, compteur + 3, color)
        next_grid = \
            make_glisseur (next_grid, 28, compteur + 25, color)
        time.sleep(0.25)
    else:
        if compteur == 1:
            time.sleep(1.2)
        if 2 <= compteur <= 300:
            next_grid = \
                make_pikachu (next_grid, 30, 70, color)
        next_grid = apply_game_of_life_rules (next_grid)
        if 2 <= compteur <= 100:
            next_grid = \
                make_pikachu (next_grid, 30, 70, color)
        if compteur == 50:
            next_grid = \
                make_glisseur (next_grid, 28, 25, color)
        if compteur == 100:
            next_grid = \
                make_glisseur (next_grid, 28, 25, color)
        if compteur == 150:
            next_grid = \
                make_glisseur (next_grid, 28,  25, color)
        if compteur == 200:
            next_grid = \
                make_glisseur (next_grid, 28,  25, color)
        if compteur == 250:
            next_grid = \
                make_glisseur (next_grid, 28, 25, color)
        if compteur == 300:
            next_grid = \
                make_glisseur (next_grid, 28,  25, color)
        if compteur ==350:
            next_grid = \
                make_glisseur (next_grid, 28,  25, color)
    return next_grid

